name: vini_verso
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  cached_network_image: ^3.1.0
  dartz: ^0.10.0
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter_bloc: ^7.2.0 
  flutter_modular: ^4.5.0
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.9
  google_fonts: ^2.2.0
  http: ^0.13.3
  intl: ^0.17.0
  mocktail: ^0.1.4
  pretty_dio_logger: ^1.1.1
  shimmer: ^2.0.0
  
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
